spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - ec2-44-198-191-170.compute-1.amazonaws.com:9092
      bindings:
        input:
          binder: kafka
          destination: test
          content-type: text/plain
          group: input-group-1
        output:
          binder: kafka
          destination: test
          group: output-group-1
          content-type: text/plain